# Generated by Django 3.2.8 on 2021-10-16 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rig', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('potencia', models.IntegerField()),
                ('tipoequipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerencia', models.CharField(max_length=3)),
                ('vicepresidencia', models.CharField(max_length=3)),
                ('campo', models.CharField(max_length=255)),
                ('pozo', models.CharField(max_length=255)),
                ('tipopozo', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('duracion', models.IntegerField()),
                ('entradaproduccion', models.DateField()),
                ('campana', models.CharField(max_length=255)),
                ('subcampana', models.CharField(max_length=255)),
                ('codigopic', models.IntegerField()),
                ('actividad', models.CharField(choices=[('ABANDONO', 'Abandono'), ('WELLSERVICE', 'WS'), ('WORKOVER', 'WO'), ('REGISTRO', 'REGISTRO'), ('EXTERNO', 'EXTERNO')], default='WORKOVER', max_length=11)),
                ('recurso', models.CharField(choices=[('CAPEX', 'CAPEX'), ('OPEX', 'OPEX'), ('ABEX', 'ABEX')], default='CAPEX', max_length=5)),
                ('rig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intervenciones.rig')),
            ],
        ),
    ]
